### ISSUE TITLE
Download on Nextcloud Apps is not working

### ISSUE THREAD

**Issue by anteprimorac** [NastuzziSamy/files_rightclick#30]
It seems like your web nastuzzi.fr is not working which breaks enabling app from Nextcloud Apps.

**Comment by virtualdxs** [comment]
I just ran into the same issue. Perhaps put the latest version on Github as part of a release file, and download it from there?

**Comment by anteprimorac** [comment]
I had downloaded the latest version from GitHub, extract it to `/apps` and still, Nextcloud tried to download it from the app store. I don't know how, but I managed to install it by changing some config.php parameters I found on similar issues.

**Comment by jsavalle** [comment]
same issue

**Comment by NastuzziSamy** [comment]
Hi guys,

I am sorry, my server is down for now, for the next versions of my apps, i will try to publish my apps on a stable platform.

Has anyone an idea ?

(I will close this issue when it will be resolved)

**Comment by virtualdxs** [comment]
@NastuzziSamy See my post above. You can host it under Releases on Github.

**Comment by virtualdxs** [comment]
For an example, see https://github.com/la5nta/pat/releases. Each of those is a static link which can be referenced anywhere.

**Comment by witzker** [comment]
How can I get this App?

**Comment by jcklpe** [comment]
Same issue here

**Comment by erikhubers** [comment]
> Hi guys,
> 
> I am sorry, my server is down for now, for the next versions of my apps, i will try to publish my apps on a stable platform.
> 
> Has anyone an idea ?
> 
> (I will close this issue when it will be resolved)

Seems a lot of people are just linking directly to the release published on GitHub (check [draw.io](https://apps.nextcloud.com/apps/drawio) for example)

**Comment by dseeker** [comment]
@NastuzziSamy Github is great for this, try that

**Comment by ArvindNair001** [comment]
### unable to install
Please  update the link in Nextcloud Apps

Error

```
Client error: `GET https://cloud.nastuzzi.fr/s/HftfHyLXNNTYmNm/download` resulted in a `404 Not Found` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found (truncated...) 
```

**Comment by daniel-wtd** [comment]
Using github-releases is quite easy and common. The cdn for github works great.

There are other ways like maxcdn, sourceforge or so, but github/gitlab releases is widely known, accessable and well integrated into other deployment processes.

**Comment by NastuzziSamy** [comment]
> ### unable to install
> 
> Please update the link in Nextcloud Apps
> 
> Error
> 
> ```
> Client error: `GET https://cloud.nastuzzi.fr/s/HftfHyLXNNTYmNm/download` resulted in a `404 Not Found` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>404 Not Found</title> </head><body> <h1>Not Found (truncated...) 
> ```

Yeah sorry I fixed it. It was caused due to Pretty urls which has broken after I updated NC: https://github.com/nextcloud/server/issues/10678

I'll release a new version at the end of the week, thanks for advice

**Comment by raynebc** [comment]
I was able to install the app today, so whatever may have changed seems to have fixed it.

**Comment by tvollscw** [comment]
I'm still getting an error: 

> cURL error 7: Failed to connect to cloud.nastuzzi.fr port 443: No route to host (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Using the latest docker image of nextcloud:fpm. Didn't have this issue with the latest Snap Package of Nextcloud.. Not sure if this is related.

**Comment by patrice-geo** [comment]
Same here.

> cURL error 7: Failed to connect to cloud.nastuzzi.fr port 443: No route to host (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by CodeBrauer** [comment]
@NastuzziSamy 
Thanks you very much for your response (#33). Do you have a date when we can expect the new version?

**Comment by GlenHuf** [comment]
FYI,  Anyone using nextcloud to host public files should try the [Share Renamer app.](https://github.com/DecaTec/sharerenamer)   With that you can customize the random part of the URL or re-instate a previously published link to fix it if it changed.   I also had trouble with the shortened url bug.

**Comment by shadowstreik** [comment]
I'm QA, speaking like QA. Nothing more. Skol!

--
CONFIDENTIALITY NOTE: Some E-Mail communication may occur using a secure
method. The information transmitted, including attachments,
is intended only for the person(s) or entity to which it is addressed and
may contain confidential and/or privileged material. Any review, re-transmission,
dissemination or other use of, or taking of any action in reliance upon this
information by persons or entities other than the intended recipient is prohibited.
If you received this in error, please contact the sender via E-Mail, only,
and destroy any copies of this information. IMPORTANT: This E-Mail is intended
for the use of the individual addressee(s) named above and may contain information
that is confidential, privileged or unsuitable for overly sensitive persons with
low self-esteem, no sense of humor or irrational religious and/or political beliefs.
Any dissemination, distribution or copying of this E-Mail is not authorized
(either explicitly or implicitly) and constitutes and irritating social faux-pas.
Also, any E-Mail sent from the originating author claims ownership of all E-Mail
sent and received on local computer(s) in addition to all non-solicited E-Mails
received. CAUTION: Unless the word 'absquatulation' has been used in its correct
context somewhere other than in this warning, it does not have any legal nor
grammatical use and may be ignored. No animals were harmed in the transmission of
this E-Mail, although the kelpie next door is living on borrowed time, let me tell
you. Those of you with an overwhelming fear of the unknown will be gratified to
learn that there is no hidden message revealed by reading this warning backwards,
so just ignore that alert notice from Microsoft. ANTIDOTE: However, by pouring a
complete circle of salt around yourself and your computer you can ensure that
no harm befalls you and your pets. If you have received this E-Mail in error,
please add some nutmeg and egg whites, whisk and place in a warm oven for 40 minutes.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pepe84** [comment]
Hi,

The error shown at Nextcloud (v14) is this one: 

`cURL error 7: Failed to connect to cloud.nastuzzi.fr port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Maybe helps.

Thanks in advance @NastuzziSamy for your time.

**Comment by NastuzziSamy** [comment]
@pepe84, it is now back online ;) 

For the release, tomorrow :)
